services:
  - type: web
    name: steakz-mis-backend
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: "npm ci && npm --workspace backend run build"
    startCommand: "npm --workspace backend run start"
    envVars:
      - key: DATABASE_URL
        fromDatabase: false
      - key: JWT_SECRET
        fromDatabase: false
      - key: JWT_EXPIRES_IN
        fromDatabase: false
      - key: PORT
        fromDatabase: false
      - key: FRONTEND_URL
        fromDatabase: false
      - key: RUN_SEED
        fromDatabase: false
