export const PERMISSIONS = {
  // Users
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_ASSIGN_ROLES: 'users.assign_roles',

  // Restaurants / Chains
  RESTAURANTS_VIEW: 'restaurants.view',
  RESTAURANTS_CREATE: 'restaurants.create',
  RESTAURANTS_EDIT: 'restaurants.edit',
  RESTAURANTS_DELETE: 'restaurants.delete',

  // Branches
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_EDIT: 'branches.edit',
  BRANCHES_DELETE: 'branches.delete',

  // Orders
  ORDERS_VIEW: 'orders.view',
  ORDERS_CREATE: 'orders.create',
  ORDERS_EDIT: 'orders.edit',
  ORDERS_CANCEL: 'orders.cancel',
  ORDERS_REFUND: 'orders.refund',

  // Reservations
  RESERVATIONS_VIEW: 'reservations.view',
  RESERVATIONS_CREATE: 'reservations.create',
  RESERVATIONS_EDIT: 'reservations.edit',
  RESERVATIONS_CANCEL: 'reservations.cancel',

  // Inventory
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_EDIT: 'inventory.edit',
  INVENTORY_DELETE: 'inventory.delete',
  INVENTORY_ADJUST_STOCK: 'inventory.adjust_stock',

  // Employees
  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_EDIT: 'employees.edit',
  EMPLOYEES_DELETE: 'employees.delete',

  // Payroll
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_PROCESS: 'payroll.process',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  // Finance
  FINANCE_VIEW: 'finance.view',
  FINANCE_MANAGE: 'finance.manage',

  // Marketing
  MARKETING_VIEW: 'marketing.view',
  MARKETING_MANAGE: 'marketing.manage',

  // Settings
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export type PermissionType = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_GROUPS = {
  USERS: [PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_EDIT, PERMISSIONS.USERS_DELETE, PERMISSIONS.USERS_ASSIGN_ROLES],
  RESTAURANTS: [PERMISSIONS.RESTAURANTS_VIEW, PERMISSIONS.RESTAURANTS_CREATE, PERMISSIONS.RESTAURANTS_EDIT, PERMISSIONS.RESTAURANTS_DELETE],
  BRANCHES: [PERMISSIONS.BRANCHES_VIEW, PERMISSIONS.BRANCHES_CREATE, PERMISSIONS.BRANCHES_EDIT, PERMISSIONS.BRANCHES_DELETE],
  ORDERS: [PERMISSIONS.ORDERS_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.ORDERS_EDIT, PERMISSIONS.ORDERS_CANCEL, PERMISSIONS.ORDERS_REFUND],
  RESERVATIONS: [PERMISSIONS.RESERVATIONS_VIEW, PERMISSIONS.RESERVATIONS_CREATE, PERMISSIONS.RESERVATIONS_EDIT, PERMISSIONS.RESERVATIONS_CANCEL],
  INVENTORY: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_EDIT, PERMISSIONS.INVENTORY_DELETE, PERMISSIONS.INVENTORY_ADJUST_STOCK],
  EMPLOYEES: [PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.EMPLOYEES_CREATE, PERMISSIONS.EMPLOYEES_EDIT, PERMISSIONS.EMPLOYEES_DELETE],
  PAYROLL: [PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_PROCESS],
  REPORTS: [PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT],
  FINANCE: [PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE],
  MARKETING: [PERMISSIONS.MARKETING_VIEW, PERMISSIONS.MARKETING_MANAGE],
  SETTINGS: [PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_MANAGE],
};
