export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  CHAIN_OWNER: 'CHAIN_OWNER',
  OPERATIONS_DIRECTOR: 'OPERATIONS_DIRECTOR',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  KITCHEN_MANAGER: 'KITCHEN_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  MARKETING_MANAGER: 'MARKETING_MANAGER',
  SUPERVISOR: 'SUPERVISOR',
  CASHIER: 'CASHIER',
  WAITER: 'WAITER',
  CHEF: 'CHEF',
  KITCHEN_STAFF: 'KITCHEN_STAFF',
  RECEPTIONIST: 'RECEPTIONIST',
  DELIVERY_DRIVER: 'DELIVERY_DRIVER',
  ACCOUNTANT: 'ACCOUNTANT',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
} as const;

export type RoleType = (typeof ROLES)[keyof typeof ROLES];

export const MANAGEMENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.OPERATIONS_DIRECTOR,
  ROLES.REGIONAL_MANAGER,
  ROLES.BRANCH_MANAGER,
];

export const USER_MANAGEMENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.HR_MANAGER,
];

export const INVENTORY_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.INVENTORY_MANAGER,
  ROLES.BRANCH_MANAGER,
];

export const FINANCE_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.FINANCE_MANAGER,
  ROLES.ACCOUNTANT,
];

export const SALES_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.FINANCE_MANAGER,
  ROLES.ACCOUNTANT,
  ROLES.BRANCH_MANAGER,
];

export const TASK_EDIT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.CHAIN_OWNER,
  ROLES.BRANCH_MANAGER,
  ROLES.OPERATIONS_DIRECTOR,
  ROLES.SUPERVISOR,
];
